### ISSUE TITLE
Deprecate the "team" alias

### ISSUE THREAD

**Issue by sleevi** [publicsuffix/publicsuffix.org#23]
Make sure we have no references to team@publicsuffix.org and that folks are steered towards psl-discuss@

**Comment by sleevi** [comment]
@dnsguru @weppos This came up from @wilsonkathleen at Mozilla noticing that her and I were the only ones on the team@ email. I'm not sure where we've got folks still pointing to this, but we should scrub them all.

**Comment by dnsguru** [comment]
@WilsonKathleen @sleevi Just put in PR #24 and also caught that we'd needed to update the (c) end dates

Please review/approve the changes

**Comment by weppos** [comment]
> @dnsguru @weppos This came up from @WilsonKathleen at Mozilla noticing that her and I were the only ones on the team@ email.

That's surprising. I am pretty sure I was on that list in the past. I guess someone run some unexpected cleanup.
