### ISSUE TITLE
Add GitHub Actions workflow to sync website to Cloud Storage

### ISSUE THREAD

**Issue by smarnach** [publicsuffix/publicsuffix.org#33]
Mozilla wants to move the static content storage for the publicsuffix.org website and the list from S3 to Googe Cloud Storage. We would also like to start using GitHub Actions to sync the files.

@Flipez will file a pull request with the Actions workflow. I already added the bucket name and some project identifiers as secrets in the repository settings. (They aren't actually secrets, but we'd prefer to keep them private.) We will use workload identity federation to authenticate to GCP, so we won't need any GCP access keys in the secrets.

Once these workflows are working as expected, I will drop my permissions on the repositories again.

**Comment by dnsguru** [comment]
You should have merge rights sven

Just request a merge if that is not the case.

I will say that my experience has been that Fridays are best to avoid big
changes on unless there are weekend resources available, in case the cjange
causes breakage

**Comment by smarnach** [comment]
Thanks, @dnsguru! I filed this ticket for transparency, and to give you or other a chance to comment. Merging the PR is not a major change. The actual change if we start actually using the new backend bucket. Until then the site is still served from the S3 origin.
