### ISSUE TITLE
MIME type for https://publicsuffix.org/list/public_suffix_list.dat changed

### ISSUE THREAD

**Issue by annevk** [publicsuffix/publicsuffix.org#37]
I can no longer view it directly in the browser.

Is this the result of 371534744854ac5e2cdb8ee2116735924596e3ad?

cc @Flipez @smarnach

**Comment by annevk** [comment]
It looks like it's still cached by some kind of intermediary. I still get `application/octet-stream` at least. Perhaps because the file itself hasn't been modified yet.

**Comment by smarnach** [comment]
Yes, this is cached in CDN. We issued an invalidation, but it will take another few minutes to complete.
